<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('master_companies')->insert([
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Reliance General Insurance Co. Ltd.',
                'company_shortname' => 'reliance',
                'logo' => 'broker_logo/logo_1745307271.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'United India Insurance',
                'company_shortname' => 'united_india',
                'logo' => 'broker_logo/logo_1745307149.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Bharti AXA General Insurance',
                'company_shortname' => 'bharti_axa',
                'logo' => 'broker_logo/logo_1745307098.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Future Generali General Insurance',
                'company_shortname' => 'future_generali',
                'logo' => 'broker_logo/logo_1745307016.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Universal Sompo General Insurance',
                'company_shortname' => 'universal_sompo',
                'logo' => 'broker_logo/logo_1745306956.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Cholamandalam MS General Insurance Co. Ltd.',
                'company_shortname' => 'cholla_mandalam',
                'logo' => 'broker_logo/logo_1745306822.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Liberty General Insurance',
                'company_shortname' => 'liberty_videocon',
                'logo' => 'broker_logo/logo_1745306719.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Shriram General Insurance Co. Ltd.',
                'company_shortname' => 'shriram',
                'logo' => 'broker_logo/logo_1745306587.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'SBI General Insurance Company Limited',
                'company_shortname' => 'sbi',
                'logo' => 'broker_logo/logo_1745306517.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Royal Sundaram General Insurance Co. Ltd.',
                'company_shortname' => 'royal_sundaram',
                'logo' => 'broker_logo/logo_1745306443.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Go Digit General Insurance Ltd.',
                'company_shortname' => 'godigit',
                'logo' => 'broker_logo/logo_1745306323.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Kotak Mahindra General',
                'company_shortname' => 'kotak',
                'logo' => 'broker_logo/logo_1745306240.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'ICICI Lombard General Insurance Co. Ltd.',
                'company_shortname' => 'icici_lombard',
                'logo' => 'broker_logo/logo_1745306084.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Bharti AXA General Insurance',
                'company_shortname' => 'bharti_axa',
                'logo' => 'broker_logo/logo_1745306051.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Magma HDI General Insurance Co. Ltd.',
                'company_shortname' => 'magma',
                'logo' => 'broker_logo/logo_1745306018.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'United India Insurance',
                'company_shortname' => 'united_india',
                'logo' => 'broker_logo/logo_1745305998.jpeg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Raheja QBE General Insurance Company Limited',
                'company_shortname' => 'raheja',
                'logo' => 'broker_logo/logo_1745305951.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Tata AIG General Insurance',
                'company_shortname' => 'tata_aig',
                'logo' => 'broker_logo/logo_1745305878.jpeg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Edelweiss General Insurance',
                'company_shortname' => 'edelweiss',
                'logo' => 'broker_logo/logo_1745305793.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Reliance General Insurance Co. Ltd.',
                'company_shortname' => 'reliance',
                'logo' => 'broker_logo/logo_1745305751.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Oriental General Insurance',
                'company_shortname' => 'oriental',
                'logo' => 'broker_logo/logo_1745305732.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'New India Assurance',
                'company_shortname' => 'new_india',
                'logo' => 'broker_logo/logo_1745305687.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'National Insurance Co. Ltd.',
                'company_shortname' => 'nic',
                'logo' => 'broker_logo/logo_1745305658.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'IFFCO Tokio General Insurance Co. Ltd.',
                'company_shortname' => 'iffco_tokio',
                'logo' => 'broker_logo/logo_1745305477.jpeg',
                'live_insu_company' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'HDFC ERGO General Insurance',
                'company_shortname' => 'hdfc_ergo',
                'logo' => 'broker_logo/logo_1745305379.jpeg',
                'live_insu_company' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'Bajaj Allianz GIC',
                'company_shortname' => 'bajaj_allianz',
                'logo' => 'broker_logo/logo_1745305133.jpeg',
                'live_insu_company' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Aditya Birla Health Insurance',
                'company_shortname' => 'aditya_birla',
                'logo' => 'broker_logo/logo_1745304804.png',
                'live_insu_company' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Star Health & Allied Insurance',
                'company_shortname' => 'star',
                'logo' => 'broker_logo/logo_1745304667.png',
                'live_insu_company' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Care Health Insurance',
                'company_shortname' => 'care_health',
                'logo' => 'broker_logo/logo_1745304510.png',
                'live_insu_company' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'HDFC ERGO General Insurance',
                'company_shortname' => 'hdfc_ergo',
                'logo' => 'broker_logo/logo_1745302328.png',
                'live_insu_company' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'MOTOR',
                'company_name' => 'ICICI Lombard General Insurance Co. Ltd.',
                'company_shortname' => 'icici_lombard',
                'logo' => 'broker_logo/logo_1745302232.jpeg',
                'live_insu_company' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Shriram Life Insurance Company Limited',
                'company_shortname' => 'shriram_life',
                'logo' => 'broker_logo/logo_1745320562.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Liberty General Insurance',
                'company_shortname' => 'liberty_general',
                'logo' => 'broker_logo/logo_1745320513.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'United India Insurance',
                'company_shortname' => 'united_india',
                'logo' => 'broker_logo/logo_1745320476.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'IFFCO-Tokio General Insurance',
                'company_shortname' => 'iffco_tokio',
                'logo' => 'broker_logo/logo_1745320386.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'The Oriental Insurance',
                'company_shortname' => 'oriental_insurance',
                'logo' => 'broker_logo/logo_1745320350.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Bajaj Allianz General Insurance',
                'company_shortname' => 'bajaj_allianz',
                'logo' => 'broker_logo/logo_1745320317.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'The New India Assurance Co. Ltd.',
                'company_shortname' => 'new_india_assurance',
                'logo' => 'broker_logo/logo_1745320276.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'National Insurance Company Limited',
                'company_shortname' => 'national_insurance',
                'logo' => 'broker_logo/logo_1745320238.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Future Generali India Insurance Company',
                'company_shortname' => 'future_generali',
                'logo' => 'broker_logo/logo_1745320192.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Reliance General Insurance',
                'company_shortname' => 'reliance_general',
                'logo' => 'broker_logo/logo_1745320082.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Raheja QBE General Insurance',
                'company_shortname' => 'raheja_qbe_general',
                'logo' => 'broker_logo/logo_1745320037.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Edelweiss General Insurance',
                'company_shortname' => 'edelweiss_general',
                'logo' => 'broker_logo/logo_1745319991.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Cholamandalam MS General Insurance Company Ltd',
                'company_shortname' => 'cholmandalam_ms',
                'logo' => 'broker_logo/logo_1745319953.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Magma HDI General Insurance',
                'company_shortname' => 'magma_hdi',
                'logo' => 'broker_logo/logo_1745319913.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'SBI Life Insurance Company Limited',
                'company_shortname' => 'sbi_life',
                'logo' => 'broker_logo/logo_1745319876.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'SBI General Insurance',
                'company_shortname' => 'sbi_general',
                'logo' => 'broker_logo/logo_1745319832.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Kotak Mahindra General Insurance',
                'company_shortname' => 'kotak_mahindra',
                'logo' => 'broker_logo/logo_1745319783.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'IndiaFirst Life Insurance Company Limited',
                'company_shortname' => 'indiafirst_life',
                'logo' => 'broker_logo/logo_1745319606.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Aditya Birla Sun Life Insurance Company Ltd.',
                'company_shortname' => 'birla_sun_life',
                'logo' => 'broker_logo/logo_1745319445.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Exide Life Insurance Company Limited',
                'company_shortname' => 'exide_life',
                'logo' => 'broker_logo/logo_1745319366.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Royal Sundaram General Insurance',
                'company_shortname' => 'royal_sundaram',
                'logo' => 'broker_logo/logo_1745319332.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Bharti AXA Life Insurance Company Limited',
                'company_shortname' => 'bharti_axa_life',
                'logo' => 'broker_logo/logo_1745319291.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Canara HSBC Oriental Bank of Commerce Life Insuran',
                'company_shortname' => 'canara_hsbc',
                'logo' => 'broker_logo/logo_1745319211.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Edelweiss Tokio Life Insurance Company Limited',
                'company_shortname' => 'edelweiss_tokio_life',
                'logo' => 'broker_logo/logo_1745319173.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'PNB MetLife India Insurance Company Limited',
                'company_shortname' => 'pnb_metlife',
                'logo' => 'broker_logo/logo_1745319140.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Aegon Life Insurance Company Limited',
                'company_shortname' => 'aegon_life',
                'logo' => 'broker_logo/logo_1745319102.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Bajaj Allianz Life Insurance Company Limited',
                'company_shortname' => 'bajaj_life',
                'logo' => 'broker_logo/logo_1745319037.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'TATA AIA Life Insurance Company Limited',
                'company_shortname' => 'tata_aia',
                'logo' => 'broker_logo/logo_1745318980.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Kotak Mahindra Life Insurance Company Limited',
                'company_shortname' => 'kotak_life',
                'logo' => 'broker_logo/logo_1745318947.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'HDFC Life Insurance Company Limited',
                'company_shortname' => 'hdfc_life',
                'logo' => 'broker_logo/logo_1745318908.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Max Life Insurance Company Limited',
                'company_shortname' => 'max_life',
                'logo' => 'broker_logo/logo_1745318860.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'ICICI Prudential Life Insurance Company Limited',
                'company_shortname' => 'icici_pru',
                'logo' => 'broker_logo/logo_1745318792.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Universal Sompo General Insurance',
                'company_shortname' => 'universal_sompo',
                'logo' => 'broker_logo/logo_1745318753.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Manipal Cigna Health Insurance',
                'company_shortname' => 'manipal_cigna',
                'logo' => 'broker_logo/logo_1745318714.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Go Digit General Insurance',
                'company_shortname' => 'go_digit',
                'logo' => 'broker_logo/logo_1745318665.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'HDFC ERGO Health Insurance',
                'company_shortname' => 'hdfc_ergo',
                'logo' => 'broker_logo/logo_1745318604.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Tata AIG General Insurance',
                'company_shortname' => 'tata_aig',
                'logo' => 'broker_logo/logo_1745318560.png',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'Niva Bupa Health Insurance',
                'company_shortname' => 'max_bupa',
                'logo' => 'broker_logo/logo_1745318515.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lobname' => 'HEALTH',
                'company_name' => 'ICICI Lombard General Insurance',
                'company_shortname' => 'icici_lombard',
                'logo' => 'broker_logo/logo_1745318480.jpg',
                'live_insu_company' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ]     
    ]);
    }
}
