<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExcelKeymaster extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('excel_key_master')->insert([
            [
                'policystatus_column_master_id' => '18',
                'excel_column_name' => 'Motor Type*',
                'sequence' => 1,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-20 05:12:39',
                'deleted_at' => null,
                'sample_data' => 'CAR (From Master)'
            ],
            [
                'policystatus_column_master_id' => '15',
                'excel_column_name' => 'Vehicle No.*',
                'sequence' => 2,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:09:45',
                'deleted_at' => null,
                'sample_data' => 'RJ-12-CN-4425'
            ],
            [
                'policystatus_column_master_id' => '4126',
                'excel_column_name' => 'Make*',
                'sequence' => 3,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:09:53',
                'deleted_at' => null,
                'sample_data' => 'HYUNDAI I20'
            ],
            [
                'policystatus_column_master_id' => '4127',
                'excel_column_name' => 'Version*',
                'sequence' => 4,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:10:01',
                'deleted_at' => null,
                'sample_data' => 'MAGNA 1.2 MT'
            ],
            [
                'policystatus_column_master_id' => '147',
                'excel_column_name' => 'RTO Code*',
                'sequence' => 5,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-20 05:12:44',
                'deleted_at' => null,
                'sample_data' => 'RJ-12'
            ],
            [
                'policystatus_column_master_id' => '4128',
                'excel_column_name' => 'Engine No.*',
                'sequence' => 6,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:20:36',
                'deleted_at' => null,
                'sample_data' => 'G4LAJM800598'
            ],
            [
                'policystatus_column_master_id' => '4129',
                'excel_column_name' => 'Chesis No.*',
                'sequence' => 7,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:20:42',
                'deleted_at' => null,
                'sample_data' => 'MALBM51BLJM516725'
            ],
            [
                'policystatus_column_master_id' => '33',
                'excel_column_name' => 'Manufacturing Date*',
                'sequence' => 8,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:20:49',
                'deleted_at' => null,
                'sample_data' => '21/01/18 (dd/mm/yyyy)'
            ],
            [
                'policystatus_column_master_id' => '96',
                'excel_column_name' => 'prev_policy_type',
                'sequence' => 9,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:20:56',
                'deleted_at' => null,
                'sample_data' => 'COMPREHENSIVE (From Master)'
            ],
            [
                'policystatus_column_master_id' => '4130',
                'excel_column_name' => 'previous_insurer_company',
                'sequence' => 10,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:21:02',
                'deleted_at' => null,
                'sample_data' => 'tata_aig (From Master)'
            ],
            [
                'policystatus_column_master_id' => '70',
                'excel_column_name' => 'OD Policy No*',
                'sequence' => 11,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:21:29',
                'deleted_at' => null,
                'sample_data' => 'D17623456'
            ],
            [
                'policystatus_column_master_id' => '30',
                'excel_column_name' => 'OD Policy Start Date*',
                'sequence' => 12,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:22:42',
                'deleted_at' => null,
                'sample_data' => '22/01/2025 (dd/mm/yyyy)'
            ],
            [
                'policystatus_column_master_id' => '4131',
                'excel_column_name' => 'OD Policy End Date*',
                'sequence' => 13,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:22:44',
                'deleted_at' => null,
                'sample_data' => '23/01/2026 (dd/mm/yyyy)'
            ],
            [
                'policystatus_column_master_id' => '4132',
                'excel_column_name' => 'TP Insurer*',
                'sequence' => 14,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:22:53',
                'deleted_at' => null,
                'sample_data' => 'Tata_Aig (From Master)'
            ],
            [
                'policystatus_column_master_id' => '4133',
                'excel_column_name' => 'TP Policy No.*',
                'sequence' => 15,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:23:27',
                'deleted_at' => null,
                'sample_data' => 'D17623456'
            ],
            [
                'policystatus_column_master_id' => '4134',
                'excel_column_name' => 'TP Policy Start Date*',
                'sequence' => 16,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:23:20',
                'deleted_at' => null,
                'sample_data' => '22/01/2025 (dd/mm/yyyy)'
            ],
            [
                'policystatus_column_master_id' => '4135',
                'excel_column_name' => 'TP Policy End Date*',
                'sequence' => 17,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 13:23:34',
                'deleted_at' => null,
                'sample_data' => '23/01/2026 (dd/mm/yyyy)'
            ],
            [
                'policystatus_column_master_id' => '31',
                'excel_column_name' => 'NCB*',
                'sequence' => 18,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:13:24',
                'deleted_at' => null,
                'sample_data' => 'NCB'
            ],
            [
                'policystatus_column_master_id' => '4136',
                'excel_column_name' => 'IDV*',
                'sequence' => 19,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-20 05:13:01',
                'deleted_at' => null,
                'sample_data' => '320000'
            ],
            [
                'policystatus_column_master_id' => '4137',
                'excel_column_name' => 'Customer Name*',
                'sequence' => 20,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:13:54',
                'deleted_at' => null,
                'sample_data' => 'Ankit Kumar'
            ],
            [
                'policystatus_column_master_id' => '4138',
                'excel_column_name' => 'Proposer Mobile No*',
                'sequence' => 21,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:13:55',
                'deleted_at' => null,
                'sample_data' => '8197176783'
            ],
            [
                'policystatus_column_master_id' => '4139',
                'excel_column_name' => 'Customer Email',
                'sequence' => 22,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:14:09',
                'deleted_at' => null,
                'sample_data' => 'ankit.kumar@xyz.com'
            ],
            [
                'policystatus_column_master_id' => '4140',
                'excel_column_name' => 'Customer DOB',
                'sequence' => 23,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:14:27',
                'deleted_at' => null,
                'sample_data' => '02/12/1997 (dd/mm/yyyy)'
            ],
            [
                'policystatus_column_master_id' => '4141',
                'excel_column_name' => 'Customer PAN',
                'sequence' => 24,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:14:39',
                'deleted_at' => null,
                'sample_data' => 'BJUFT7778K'
            ],
            [
                'policystatus_column_master_id' => '4142',
                'excel_column_name' => 'Customer Address',
                'sequence' => 25,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:15:06',
                'deleted_at' => null,
                'sample_data' => 'Customer Address'
            ],
            [
                'policystatus_column_master_id' => '4143',
                'excel_column_name' => 'Customer PinCode',
                'sequence' => 26,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:15:08',
                'deleted_at' => null,
                'sample_data' => '400005'
            ],
            [
                'policystatus_column_master_id' => '4144',
                'excel_column_name' => 'Customer City',
                'sequence' => 27,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:15:09',
                'deleted_at' => null,
                'sample_data' => 'Mumbai'
            ],
            [
                'policystatus_column_master_id' => '4145',
                'excel_column_name' => 'Customer State',
                'sequence' => 28,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:15:11',
                'deleted_at' => null,
                'sample_data' => 'Maharashtra'
            ],
            [
                'policystatus_column_master_id' => '55',
                'excel_column_name' => 'CPA',
                'sequence' => 29,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:15:23',
                'deleted_at' => null,
                'sample_data' => 'YES / NO'
            ],
            [
                'policystatus_column_master_id' => '97',
                'excel_column_name' => 'NilDep',
                'sequence' => 30,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:15:24',
                'deleted_at' => null,
                'sample_data' => 'YES / NO'
            ],
            [
                'policystatus_column_master_id' => '95',
                'excel_column_name' => 'Policy Type*',
                'sequence' => 31,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:15:48',
                'deleted_at' => null,
                'sample_data' => 'rollover  (From Master)'
            ],
            [
                'policystatus_column_master_id' => '4146',
                'excel_column_name' => 'Basic OD*',
                'sequence' => 32,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:16:38',
                'deleted_at' => null,
                'sample_data' => '5086'
            ],
            [
                'policystatus_column_master_id' => '4147',
                'excel_column_name' => 'Basic TP*',
                'sequence' => 33,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:16:40',
                'deleted_at' => null,
                'sample_data' => '3416'
            ],
            [
                'policystatus_column_master_id' => '50',
                'excel_column_name' => 'Total Premium*',
                'sequence' => 34,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:17:16',
                'deleted_at' => null,
                'sample_data' => '10092'
            ],
            [
                'policystatus_column_master_id' => '51',
                'excel_column_name' => 'Net Premium*',
                'sequence' => 35,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:17:39',
                'deleted_at' => null,
                'sample_data' => '8552'
            ],
            [
                'policystatus_column_master_id' => '52',
                'excel_column_name' => 'Service Tax*',
                'sequence' => 36,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:18:32',
                'deleted_at' => null,
                'sample_data' => '1540'
            ],
            [
                'policystatus_column_master_id' => '23',
                'excel_column_name' => 'Vehicle Fuel*',
                'sequence' => 37,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:18:56',
                'deleted_at' => null,
                'sample_data' => 'PETROL (From Master)'
            ],
            [
                'policystatus_column_master_id' => '4148',
                'excel_column_name' => 'Policy Issue Date*',
                'sequence' => 38,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:19:15',
                'deleted_at' => null,
                'sample_data' => '24/01/25  (dd/mm/yyyy)'
            ],
            [
                'policystatus_column_master_id' => '4149',
                'excel_column_name' => 'Cubic Capacity*',
                'sequence' => 39,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:19:15',
                'deleted_at' => null,
                'sample_data' => '1197'
            ],
            [
                'policystatus_column_master_id' => '56',
                'excel_column_name' => 'AddOn Premium*',
                'sequence' => 40,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:20:16',
                'deleted_at' => null,
                'sample_data' => '100'
            ],
            [
                'policystatus_column_master_id' => '54',
                'excel_column_name' => 'Gross Discount',
                'sequence' => 41,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:20:28',
                'deleted_at' => null,
                'sample_data' => '100'
            ],
            [
                'policystatus_column_master_id' => '49',
                'excel_column_name' => 'Total Tp*',
                'sequence' => 42,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:20:45',
                'deleted_at' => null,
                'sample_data' => '3466'
            ],
            [
                'policystatus_column_master_id' => '26',
                'excel_column_name' => 'Vehicle GVW',
                'sequence' => 43,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:21:11',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '24',
                'excel_column_name' => 'Seating Capacity',
                'sequence' => 44,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:21:50',
                'deleted_at' => null,
                'sample_data' => '5'
            ],
            [
                'policystatus_column_master_id' => '4150',
                'excel_column_name' => 'Previous Policy Number*',
                'sequence' => 45,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:22:01',
                'deleted_at' => null,
                'sample_data' => 'OG-24-1105-1801-00002007'
            ],
            [
                'policystatus_column_master_id' => '4151',
                'excel_column_name' => 'Previous NCB',
                'sequence' => 46,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:22:16',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4152',
                'excel_column_name' => 'Employee Mobile Number',
                'sequence' => 47,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:28:55',
                'deleted_at' => null,
                'sample_data' => 'Mapped Employee, Pos or Partner any one mobile number'
            ],
            [
                'policystatus_column_master_id' => '4153',
                'excel_column_name' => 'POS Username',
                'sequence' => 48,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:28:56',
                'deleted_at' => null,
                'sample_data' => 'Mapped Employee, Pos or Partner any one mobile number'
            ],
            [
                'policystatus_column_master_id' => '4154',
                'excel_column_name' => 'Partner Username',
                'sequence' => 49,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:28:57',
                'deleted_at' => null,
                'sample_data' => 'Mapped Employee, Pos or Partner any one mobile number'
            ],
            [
                'policystatus_column_master_id' => '4155',
                'excel_column_name' => 'registration_date',
                'sequence' => 50,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:04',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4156',
                'excel_column_name' => 'vehicle_colour',
                'sequence' => 51,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:05',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4157',
                'excel_column_name' => 'vehicle_uses_type_cv',
                'sequence' => 52,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:06',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4158',
                'excel_column_name' => 'vehicle_carrier_type',
                'sequence' => 53,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:07',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4159',
                'excel_column_name' => 'previous_claim_status',
                'sequence' => 54,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:09',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4160',
                'excel_column_name' => 'previous_claim_amount',
                'sequence' => 55,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:09',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4161',
                'excel_column_name' => 'no_of_claims',
                'sequence' => 56,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:10',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4162',
                'excel_column_name' => 'cpa_opt-out_reason',
                'sequence' => 57,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:12',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4163',
                'excel_column_name' => 'transefer_of_ownership',
                'sequence' => 58,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:13',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4164',
                'excel_column_name' => 'financier_agreement_type',
                'sequence' => 59,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:14',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4165',
                'excel_column_name' => 'financier_name',
                'sequence' => 60,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:18',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4166',
                'excel_column_name' => 'financier_city_branch',
                'sequence' => 61,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:20',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4167',
                'excel_column_name' => 'puc_end_date',
                'sequence' => 62,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:21',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4168',
                'excel_column_name' => 'puc_number',
                'sequence' => 63,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:22',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '86',
                'excel_column_name' => 'owner_type',
                'sequence' => 64,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:22',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '1154',
                'excel_column_name' => 'occupation',
                'sequence' => 65,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:23',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4170',
                'excel_column_name' => 'marital_status',
                'sequence' => 66,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:24',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4171',
                'excel_column_name' => 'eai_number',
                'sequence' => 67,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:25',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4172',
                'excel_column_name' => 'gst_no',
                'sequence' => 68,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:25',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4173',
                'excel_column_name' => 'gender Male',
                'sequence' => 69,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:27',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '78',
                'excel_column_name' => 'nominee_name',
                'sequence' => 70,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:35',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '75',
                'excel_column_name' => 'nominee_dob',
                'sequence' => 71,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:35',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4174',
                'excel_column_name' => 'relationship_with_nominee',
                'sequence' => 72,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:36',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4175',
                'excel_column_name' => 'vehicle_registration_address',
                'sequence' => 73,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:37',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [

                'policystatus_column_master_id' => '4176',
                'excel_column_name' => 'vehicle_registration_pincode',
                'sequence' => 74,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:38',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4177',
                'excel_column_name' => 'vehicle_registration_state',
                'sequence' => 75,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:39',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4178',
                'excel_column_name' => 'vehicle_registration_city',
                'sequence' => 76,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:39',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4179',
                'excel_column_name' => 'rsa',
                'sequence' => 77,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:40',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4180',
                'excel_column_name' => 'consumable',
                'sequence' => 78,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:41',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4181',
                'excel_column_name' => 'key_replacement',
                'sequence' => 79,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:42',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4182',
                'excel_column_name' => 'engine_protector',
                'sequence' => 80,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:43',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4183',
                'excel_column_name' => 'ncb_protection',
                'sequence' => 81,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:44',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4184',
                'excel_column_name' => 'tyre_secure',
                'sequence' => 82,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:44',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4185',
                'excel_column_name' => 'return_to_invoice',
                'sequence' => 83,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:45',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4186',
                'excel_column_name' => 'loss_of_personal_belonging',
                'sequence' => 84,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:03:46',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4187',
                'excel_column_name' => 'electrical_si_amount',
                'sequence' => 85,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:25',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4188',
                'excel_column_name' => 'not-electrical',
                'sequence' => 86,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:26',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4189',
                'excel_column_name' => 'external_bifuel_cng_lpg',
                'sequence' => 87,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:27',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4190',
                'excel_column_name' => 'pa_cover_for_additional_paid_driver',
                'sequence' => 88,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:28',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4191',
                'excel_column_name' => 'unnammed_passenger_pa_cover',
                'sequence' => 89,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:30',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4192',
                'excel_column_name' => 'll_paid_driver',
                'sequence' => 90,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:31',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4193',
                'excel_column_name' => 'geogarphical_extension',
                'sequence' => 91,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:32',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4194',
                'excel_column_name' => 'arai_approved',
                'sequence' => 92,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:33',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4195',
                'excel_column_name' => 'voluntary_deductible_si_amount',
                'sequence' => 93,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:34',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4196',
                'excel_column_name' => 'tppd_cover',
                'sequence' => 94,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:35',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4197',
                'excel_column_name' => 'cv_zero_dep',
                'sequence' => 95,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:21',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4198',
                'excel_column_name' => 'cv_rsa',
                'sequence' => 96,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:20',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4199',
                'excel_column_name' => 'cv_imt_23',
                'sequence' => 97,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:18',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4200',
                'excel_column_name' => 'cv_electrical_si_amount',
                'sequence' => 98,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:17',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4201',
                'excel_column_name' => 'cv_not-electrical',
                'sequence' => 99,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:16',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4202',
                'excel_column_name' => 'cv_external_bifuel_cng_lpg',
                'sequence' => 100,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:15',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4203',
                'excel_column_name' => 'cv_ll_paid_driver',
                'sequence' => 101,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:14',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4204',
                'excel_column_name' => 'cv_ll_paid_conductor',
                'sequence' => 102,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:13',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4205',
                'excel_column_name' => 'cv_ll_paid_coolie',
                'sequence' => 103,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:11',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4206',
                'excel_column_name' => 'cv_ll_paid_cleaner',
                'sequence' => 104,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:11',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4207',
                'excel_column_name' => 'cv_pa_paid_driver',
                'sequence' => 105,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:10',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4208',
                'excel_column_name' => 'cv_pa_paid_conductor',
                'sequence' => 106,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:09',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4209',
                'excel_column_name' => 'cv_pa_paid_cleaner',
                'sequence' => 107,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:09',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4210',
                'excel_column_name' => 'cv_geogarphical_extension',
                'sequence' => 108,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:08',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4211',
                'excel_column_name' => 'cv_vehicle_limited_to_own_premissis',
                'sequence' => 109,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:07',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4212',
                'excel_column_name' => 'cv_tppd',
                'sequence' => 110,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-13 07:04:06',
                'deleted_at' => null,
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '4213',
                'excel_column_name' => 'Action',
                'sequence' => 111,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => null,
                'updated_at' => '2025-03-12 15:24:38',
                'deleted_at' => null,
                'sample_data' => 'migrate or update'
            ],
            [
                'policystatus_column_master_id' => '975',
                'excel_column_name' => 'migration_uploaded_at',
                'sequence' => null,
                'is_visible' => 'N',
                'lob_id' => 'PCV',
                'created_at' => null,
                'updated_at' => '2025-02-21 06:14:45',
                'deleted_at' => '2025-02-21 06:14:45',
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '481',
                'excel_column_name' => 'gender_name',
                'sequence' => null,
                'is_visible' => 'N',
                'lob_id' => 'CAR',
                'created_at' => null,
                'updated_at' => '2025-02-21 08:33:45',
                'deleted_at' => '2025-02-21 08:33:45',
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '9',
                'excel_column_name' => 'cng_tp',
                'sequence' => 100,
                'is_visible' => 'Y',
                'lob_id' => 'CAR',
                'created_at' => null,
                'updated_at' => '2025-03-10 09:34:35',
                'deleted_at' => '2025-02-21 08:34:20',
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '2',
                'excel_column_name' => 'policy_tenture_days',
                'sequence' => 20,
                'is_visible' => 'Y',
                'lob_id' => 'CAR',
                'created_at' => null,
                'updated_at' => '2025-03-10 09:34:35',
                'deleted_at' => '2025-02-21 08:33:57',
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '463',
                'excel_column_name' => 'vehicle_cubic_capacity',
                'sequence' => null,
                'is_visible' => 'N',
                'lob_id' => 'CAR',
                'created_at' => null,
                'updated_at' => '2025-02-21 08:36:39',
                'deleted_at' => '2025-02-21 08:36:39',
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '458',
                'excel_column_name' => 'cover_amount',
                'sequence' => null,
                'is_visible' => 'N',
                'lob_id' => 'CAR',
                'created_at' => null,
                'updated_at' => '2025-02-21 08:36:37',
                'deleted_at' => '2025-02-21 08:36:37',
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '455',
                'excel_column_name' => 'proposer_emailid',
                'sequence' => null,
                'is_visible' => 'N',
                'lob_id' => 'CAR',
                'created_at' => null,
                'updated_at' => '2025-02-21 08:36:02',
                'deleted_at' => '2025-02-21 08:36:02',
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '479',
                'excel_column_name' => 'company_name',
                'sequence' => null,
                'is_visible' => 'N',
                'lob_id' => 'CAR',
                'created_at' => null,
                'updated_at' => '2025-02-21 08:36:15',
                'deleted_at' => '2025-02-21 08:36:15',
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '482',
                'excel_column_name' => 'proposer_gender',
                'sequence' => null,
                'is_visible' => 'N',
                'lob_id' => 'CAR',
                'created_at' => null,
                'updated_at' => '2025-02-21 08:36:20',
                'deleted_at' => '2025-02-21 08:36:20',
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '491',
                'excel_column_name' => 'premium_amount',
                'sequence' => null,
                'is_visible' => 'N',
                'lob_id' => 'CAR',
                'created_at' => null,
                'updated_at' => '2025-02-21 08:36:36',
                'deleted_at' => '2025-02-21 08:36:36',
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '488',
                'excel_column_name' => 'proposer_dob',
                'sequence' => null,
                'is_visible' => 'N',
                'lob_id' => 'CAR',
                'created_at' => null,
                'updated_at' => '2025-02-21 08:36:35',
                'deleted_at' => '2025-02-21 08:36:35',
                'sample_data' => null
            ],
            [
                'policystatus_column_master_id' => '92',
                'excel_column_name' => 'Policy URL',
                'sequence' => 112,
                'is_visible' => null,
                'lob_id' => null,
                'created_at' => '2025-03-12 15:25:57',
                'updated_at' => '2025-03-12 15:25:57',
                'deleted_at' => null,
                'sample_data' => 'Policy URL'
            ],
            [
                'policystatus_column_master_id' => '92',
                'excel_column_name' => 'Policy Copy URL',
                'sequence' => 112,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => '2025-03-13 05:49:24',
                'updated_at' => '2025-03-13 08:10:07',
                'deleted_at' => null,
                'sample_data' => 'Policy Copy URL'
            ],
            [
                'policystatus_column_master_id' => '4215',
                'excel_column_name' => 'test100',
                'sequence' => 1,
                'is_visible' => null,
                'lob_id' => null,
                'created_at' => '2025-03-13 04:58:06',
                'updated_at' => '2025-03-13 04:58:06',
                'deleted_at' => null,
                'sample_data' => 'test'
            ],
            [
                'policystatus_column_master_id' => '4215',
                'excel_column_name' => 'test',
                'sequence' => 3,
                'is_visible' => null,
                'lob_id' => null,
                'created_at' => '2025-03-13 05:11:17',
                'updated_at' => '2025-03-13 05:11:17',
                'deleted_at' => null,
                'sample_data' => 'test'
            ],
            [
                'policystatus_column_master_id' => '4216',
                'excel_column_name' => 'test1',
                'sequence' => 3,
                'is_visible' => null,
                'lob_id' => null,
                'created_at' => '2025-03-13 05:12:37',
                'updated_at' => '2025-03-13 05:12:37',
                'deleted_at' => null,
                'sample_data' => 'test1'
            ],
            [
                'policystatus_column_master_id' => '4217',
                'excel_column_name' => 'asdasd',
                'sequence' => 2,
                'is_visible' => null,
                'lob_id' => null,
                'created_at' => '2025-03-13 05:13:38',
                'updated_at' => '2025-03-13 05:13:38',
                'deleted_at' => null,
                'sample_data' => 'dsafa'
            ],
            [
                'policystatus_column_master_id' => '4218',
                'excel_column_name' => 'sfdsd',
                'sequence' => 3,
                'is_visible' => null,
                'lob_id' => null,
                'created_at' => '2025-03-13 05:13:49',
                'updated_at' => '2025-03-13 05:13:49',
                'deleted_at' => null,
                'sample_data' => 'fsdf'
            ],
            [
                'policystatus_column_master_id' => '4219',
                'excel_column_name' => 'dasd',
                'sequence' => 1,
                'is_visible' => null,
                'lob_id' => '2',
                'created_at' => '2025-03-13 05:15:53',
                'updated_at' => '2025-03-13 05:15:53',
                'deleted_at' => null,
                'sample_data' => 'das'
            ],
            [
                'policystatus_column_master_id' => '92',
                'excel_column_name' => 'Policy Copy URL',
                'sequence' => 112,
                'is_visible' => 'Y',
                'lob_id' => '1',
                'created_at' => '2025-03-13 05:49:24',
                'updated_at' => '2025-03-13 08:10:07',
                'deleted_at' => null,
                'sample_data' => 'Policy Copy URL'
            ]
        ]);
    }
}
